name: Verify

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      # Setup dependency caching
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        env:
          CI: true
        run: |
          yarn install --frozen-lockfile
 
      - name: Run Unit Tests + Coverage
        run: yarn test:cov

      - name: Build
        run: yarn build

      - name: Upload Coverage + Climate
        if: success()
        env:
          CI: true
          CODE_COV: ${{ secrets.CODE_COV }}
          CODECLIMATE_REPO_TOKEN: ${{ secrets.CODE_CLIMATE }}
        run: |
          # Upload to Code Cover. Curl used in place of codecov/codecov-action
          # due to long build time. See https://github.com/codecov/codecov-action/issues/21
          curl -s https://codecov.io/bash | bash -s -- -t $CODE_COV
          # Install codeclimate tool and upload
          npm install -g codeclimate-test-reporter
          codeclimate-test-reporter < coverage/lcov.info